#!/usr/bin/env bash
set -u
set -e

# This must be run from the repo root directory
cd "$(dirname "$0")"

NAME="game_2021"

cargo build --release
rm -rf "${NAME:-/tmp/foo}" "${NAME:-/tmp/foo}.zip"
mkdir -p "$NAME"
cp "target/release/$NAME" "$NAME/"
git ls-files assets | rsync -a --files-from=- . "$NAME"
# Add the commit hash.
git show -q --format=format:%H > "$NAME/commit.txt"
zip -r "$NAME.zip" "$NAME/"
