#!/usr/bin/env bash
set -u
set -e

if ! git diff --cached --exit-code --quiet
then
    >&2 echo "Can't release when there are staged changes"
    exit 1
fi

# This must be run from the repo root directory
cd "$(dirname "$0")"

NAME="game_2021"

cargo build --release
rm -rf "${NAME:-/tmp/foo}" "${NAME:-/tmp/foo}.zip"
mkdir -p "$NAME"
cp "target/release/$NAME" "$NAME/"
# Copy assets.
for asset in $(git ls-files assets)
do
    asset_dir="$(dirname "$asset")"
    mkdir -p "$NAME/$asset_dir"
    cp "$asset" "$NAME/$asset_dir/"
done

# Add the commit hash.
git show -q --format=format:%H > "$NAME/commit.txt"

# Create a branch and commit the release.
branch="release-$(date '+%Y-%m-%d-%H%M%S')"
git checkout -b "$branch"
git add -f "$NAME"
git commit -m "Release"
# Use git to zip since we can't rely on external dependencies.
git archive --format=zip -o "$NAME.zip" HEAD "$NAME"
# Restore state and clean up.
git checkout -
git branch -D "$branch"
