[package]
name = "game_2021"
description = "A 2d game engine on top of Bevy."
version = "0.2.1"
authors = ["Jonathan Tran <jonnytran@gmail.com>", "Daniel Taub <dmtaub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.36"
bevy = { git = "https://github.com/bevyengine/bevy/", rev="c3a72e9dc85b53a1448138270c72e806fc91ec85", features = ["vorbis"] }
bevy_tiled_prototype = { git = "https://github.com/StarArawn/bevy_tiled", branch = "main" }
ncollide2d = "0.27.0"
ron = "0.6.4"
serde = "^1.0.123"

# [patch.'https://github.com/StarArawn/bevy_tiled']
# bevy_tiled_prototype = { path = "../bevy_tiled" }

[profile.dev.package."*"]
# Optimize dependencies.
opt-level = 3
