[package]
name = "game_2021"
version = "0.1.0"
authors = ["Jonathan Tran <jonnytran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4.0", features = ["vorbis"] }
bevy_asset_ron = { git = "https://github.com/jamadazi/bevy_asset_ron", branch = "master" }
bevy_tiled_prototype = { git = "https://github.com/dmtaub/bevy_tiled", branch = "items" }
ncollide2d = "0.27.0"
ron = "0.6.4"
serde = "^1.0.123"

# [patch.'https://github.com/dmtaub/bevy_tiled']
# bevy_tiled_prototype = { path = "../bevy_tiled" }

[profile.dev.package."*"]
# Optimize dependencies.
opt-level = 3
