# Settings for a new game.
title = "Celebration 2021: Twodina"

# Path is relative to /assets and shouldn't start with a /.
start_map = "maps/sandyrocks.tmx"
map_scale = 2.0
start_dialogue = "dialogue/level1.dialogue"
#start_map = "../../bevy_tiled/assets/ortho-debug.tmx"
#map_scale = 4.0

# Characters to use - for multiple, {} will be replaced:
char_template = "sprites/azuna{}.png"
char_height = 31.0
char_width = 32.0

# char_template = "sprites/naked_base.png"
# char_height = 26.0
# char_width = 36.0

walk_speed = 175.0
run_speed = 400.0
